### ISSUE TITLE
codehskarel

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies-archive/codehskarel-tester#1]
ბრძანებებისთვის სახელების შეცვლა.

turnRight() შეუძლია კარელს.
codehs-ზე წერია რა პირობები შეუძლია შეამოწმოს და ყველა დაამატე, ყველას კი არ განვიხილავ მარა მაინც იყოს

https://github.com/freeuni-digital-technologies/codehskarel-tester

**Comment by khokho** [comment]
დავამატე და ტესტებიც დავუწერე. წესით მუშაობს. 

https://github.com/freeuni-digital-technologies/codehskarel-tester/commit/179b661299a48c4b46621354b9215cb7af8f8e74

[jskarel 80d7b356d](
https://github.com/freeuni-digital-technologies/jskarel/commit/80d7b356d0382a3e58368aa0720c31219c624954)

**Comment by iarigby** [comment]
👍

**Comment by iarigby** [comment]
ჯერ დავტოვებ open-ს, რავიცი რამე ახალი ბრძანებები არ გაჩითონ :დ

**Comment by iarigby** [comment]
15 საათი შემყავდა წინა სემესტრის გადაბარების კითხვები, ისე ჭედავს მუდლი და შემდეგი ორი კვირა ჯერ ჰაერშია. არადა სამსახურიც მაქვს T-T
